services:
  - type: web
    name: ai-crm-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALGORITHM
        value: HS256
      - key: PYTHON_VERSION
        value: 3.11.0
